package:
    name: psrtools
    version: {{ GIT_DESCRIBE_TAG }}

build:
    number: {{ GIT_DESCRIBE_NUMBER }}

source:
    git_url: ..

requirements:
    build:
        - {{ compiler('cxx') }}
        - make
        - perl
    host:
        - psrchive
    run:
        - psrchive

test:
    commands:
        - autotoa -h
        - normalize_rms -h

about:
    home: https://github.com/demorest/psrtools
